<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Capital' => '',
    'Cities' => 'Cidades',
    'City' => 'Cidade',
    'Code' => '',
    'Code2' => '',
    'Congratulations' => 'Parabéns',
    'Continent' => '',
    'Countries' => 'Países',
    'Country Code' => '',
    'Country Language' => 'Idioma do País',
    'Country Languages' => '',
    'Create Country' => '',
    'Create Country Language' => '',
    'Create Teste' => '',
    'Create {model}' => 'Cadastrar {model}',
    'Delete' => 'Excluir',
    'District' => '',
    'Gnp' => '',
    'Gnpold' => '',
    'Government Form' => '',
    'Head Of State' => '',
    'ID' => '',
    'Indep Year' => '',
    'Is Official' => '',
    'Language' => 'Idioma',
    'Life Expectancy' => '',
    'Local Name' => '',
    'Name' => 'Nome',
    'Percentage' => 'Porcentagem',
    'Population' => '',
    'Region' => '',
    'Reset' => '',
    'Save' => 'Salvar',
    'Search' => '',
    'Surface Area' => '',
    'Testes' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update City: mode' => '',
    'Update Country Language: mode' => '',
    'Update Country: mode' => '',
    'Update Teste: mode' => '',
    'We have {a,plural,=1{# student} other{# students}}' => 'Nós temos {a,plural,=1{# estudante} other {# estudantes}}',
];
